version: "3.5"
services:
  api1:
    # image: oliveigah/rinha-backend-v3:0.0.1
    build: .
    hostname: api1.com
    networks:
      - payment-processor
    environment:
      ERL_MAX_PORTS: 2048
      HTTP_SERVER_PORT: 3000
      RELEASE_COOKIE: "secret_cookie"
      RELEASE_NODE: "api@api1.com"
      RELEASE_DISTRIBUTION: "name"
      BOOTSTRAP_NODES: "api@api2.com"
      PROCESSORS_COUNT: 1
    healthcheck:
      test: curl -f http://api1:3000
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "150MB"

  api2:
    # image: oliveigah/rinha-backend-v3:0.0.1
    build: .
    networks:
      - payment-processor
    hostname: api2.com
    environment:
      ERL_MAX_PORTS: 2048
      HTTP_SERVER_PORT: 3000
      RELEASE_COOKIE: "secret_cookie"
      RELEASE_NODE: "api@api2.com"
      RELEASE_DISTRIBUTION: "name"
      BOOTSTRAP_NODES: "api@api1.com"
      PROCESSORS_COUNT: 1
    healthcheck:
      test: curl -f http://api2:3000
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "150MB"

  nginx:
    image: nginx:latest
    networks:
      - payment-processor
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
